In [3]:
import pandas as pd

In [4]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  human
1  robot
2  human
3  robot
4  robot

In [9]:
data.loc[data['whoAmI'] == 'human', 'human'] = '1'
data.loc[data['whoAmI'] != 'human', 'human'] = '0'
data.loc[data['whoAmI'] == 'robot', 'robot'] = '1'
data.loc[data['whoAmI'] != 'robot', 'robot'] = '0'
data.head()

  whoAmI human robot
0  human     1     0
1  robot     0     1
2  human     1     0
3  robot     0     1
4  robot     0     1